const express = require("express");
const db = require("../database");

const router = express.Router();

// Test Route
router.get("/", (req, res) => {
  res.send("hello world");
});

// ### DATA MANAGEMENT ###

// ### M-CUSTOMERS ###
// Get All Customers data
router.get("/management/customers/all", (req, res) => {
  db.query("SELECT * FROM customers ORDER BY CustomerId ASC", (err, result) => {
    if (err) {
      console.log(err);
    } else {
      res.status(200).send(result.rows);
    }
  });
});

// Get A Certain Customer data
router.get("/management/customers/certain/:id", (req, res) => {
  const id = req.params.id;
  db.query(
    "SELECT * FROM customers WHERE CustomerId = $1",
    [id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Add A Customer
router.post("/management/customers/add", (req, res) => {
  const { name, uuid, dob, type, balance } = req.body;
  // created_at, last_modified, is_active are automatically generated by the database
  db.query(
    "INSERT INTO customers (CustomerName, CustomerUuid, DateOfBirth, Balance, EncryptionType) VALUES ($1, $2, $3, $4, $5)",
    [name, uuid, dob, balance, type],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send("customer added successfully");
      }
    }
  );
});

// Update A Customer data
router.patch("/management/customers/update/:id", (req, res) => {
  const id = req.params.id;
  const { name, uuid, dob, balance, type } = req.body;
  db.query(
    "UPDATE customers SET CustomerName = $1, CustomerUuid = $2, DateOfBirth = $3, Balance = $4, EncryptionType = $5 WHERE CustomerId = $6",
    [name, uuid, dob, balance, type, id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send("customer updated successfully");
      }
    }
  );
});

// Delete A Customer
router.delete("/management/customers/delete/:id", (req, res) => {
  const id = req.params.id;
  db.query(
    "DELETE FROM customers WHERE CustomerId = $1",
    [id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send("customer deleted successfully");
      }
    }
  );
});

// ### M-SPOTS ###

// Get All Spots data
router.get("/management/spots/all", (req, res) => {
  db.query("SELECT * FROM spots ORDER BY SpotId ASC", (err, result) => {
    if (err) {
      console.log(err);
    } else {
      res.status(200).send(result.rows);
    }
  });
});

// Get A Certain Spot data
router.get("/management/spots/certain/:id", (req, res) => {
  const id = req.params.id;
  db.query("SELECT * FROM spots WHERE SpotId = $1", [id], (err, result) => {
    if (err) {
      console.log(err);
    } else {
      res.status(200).send(result.rows);
    }
  });
});

// Add A Spot
router.post("/management/spots/add", (req, res) => {
  const { name, uuid, price } = req.body;
  // created_at, last_modified, is_active are automatically generated by the database
  db.query(
    "INSERT INTO spots (SpotName, SpotUuid, Price) VALUES ($1, $2, $3)",
    [name, uuid, price],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send("spot added successfully");
      }
    }
  );
});

// Update A Spot data
router.patch("/management/spots/update/:id", (req, res) => {
  const id = req.params.id;
  const { name, uuid, price } = req.body;
  db.query(
    "UPDATE spots SET SpotName = $1, SpotUuid = $2, Price = $3 WHERE SpotId = $4",
    [name, uuid, price, id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send("spot updated successfully");
      }
    }
  );
});

// Delete A Spot
router.delete("/management/spots/delete/:id", (req, res) => {
  const id = req.params.id;
  db.query("DELETE FROM spots WHERE SpotId = $1", [id], (err, result) => {
    if (err) {
      console.log(err);
    } else {
      res.status(200).send("spot deleted successfully");
    }
  });
});

// ### ACTIVATION ###

// Activate/Deactivate a Customer
router.patch("/activation/customer/:id", (req, res) => {
  const id = req.params.id;
  const { new_status } = req.body;
  db.query(
    "UPDATE customers SET IsActive = $1 WHERE CustomerId = $2",
    [new_status, id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send("customer activation updated successfully");
      }
    }
  );
});

// Activate/Deactivate a Spot
router.patch("/activation/spot/:id", (req, res) => {
  const id = req.params.id;
  const { new_status } = req.body;
  db.query(
    "UPDATE spots SET IsActive = $1 WHERE SpotId = $2",
    [new_status, id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send("spot activation updated successfully");
      }
    }
  );
});

// Check Activation of A Customer
router.get("/activation/customer/:id", (req, res) => {
  const id = req.params.id;
  db.query(
    "SELECT IsActive FROM customers WHERE CustomerId = $1",
    [id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// ### DEPOSITS ###

// Get All Deposits data
router.get("/deposits/all", (req, res) => {
  db.query("SELECT * FROM deposits ORDER BY DepositId ASC", (err, result) => {
    if (err) {
      console.log(err);
    } else {
      res.status(200).send(result.rows);
    }
  });
});

// Get Deposit data of A Certain Customer
router.get("/deposits/certain/customers/:id", (req, res) => {
  const id = req.params.id;
  db.query(
    "SELECT * FROM deposits WHERE CustomerId = $1 ORDER BY DepositId ASC",
    [id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Add A Deposit of A Customer
router.post("/deposits/add", (req, res) => {
  const { customer_id, amount } = req.body;
  console.log(customer_id, amount);
  // DepositTimestamp is automatically generated by the database
  // insert data to deposits table and update balance in customers table
  db.query(
    "INSERT INTO deposits (CustomerId, Amount) VALUES ($1, $2)",
    [customer_id, amount],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        // update balance in customers table
        db.query(
          "UPDATE customers SET Balance = Balance + $1 WHERE CustomerId = $2",
          [amount, customer_id],
          (err, result) => {
            if (err) {
              console.log(err);
              // if error occurs, delete the last deposit was made
              let lastDepositDeleted = false;
              do {
                db.query(
                  "DELETE FROM deposits WHERE DepositId = (SELECT MAX(DepositId) FROM deposits)",
                  (err, result) => {
                    if (err) {
                      console.log(err);
                    } else {
                      lastDepositDeleted = true;
                    }
                  }
                );
              } while (!lastDepositDeleted);
            } else {
              res.status(200).send("deposit added successfully");
            }
          }
        );
      }
    }
  );
});

// ### PAYMENTS ###

// Get All Payments data
router.get("/payments/all", (req, res) => {
  db.query("SELECT * FROM payments ORDER BY PaymentId ASC", (err, result) => {
    if (err) {
      console.log(err);
    } else {
      res.status(200).send(result.rows);
    }
  });
});

// Get Payment data of A Certain Customer
router.get("/payments/certain/customers/:id", (req, res) => {
  const id = req.params.id;
  db.query(
    "SELECT * FROM payments WHERE CustomerId = $1 ORDER BY PaymentId ASC",
    [id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Get Payment data of A Certain Spot
router.get("/payments/certain/spots/:id", (req, res) => {
  const id = req.params.id;
  db.query(
    "SELECT * FROM payments WHERE SpotId = $1 ORDER BY PaymentId ASC",
    [id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Add A Payment of A Customer in A Spot
router.post("/payments/add", (req, res) => {
  const { customer_id, spot_id } = req.body;
  // PaymentTimestamp is automatically generated by the database
  // insert data to payments table and update balance in customers table, balance update is subtracting old balance with price of the spot
  db.query(
    "INSERT INTO payments (CustomerId, SpotId) VALUES ($1, $2)",
    [customer_id, spot_id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        // update balance in customers table
        db.query(
          "UPDATE customers SET Balance = Balance - (SELECT Price FROM spots WHERE SpotId = $1) WHERE CustomerId = $2",
          [spot_id, customer_id],
          (err, result) => {
            if (err) {
              console.log(err);
              // if error occurs, delete the last payment was made
              let lastPaymentDeleted = false;
              do {
                db.query(
                  "DELETE FROM payments WHERE PaymentId = (SELECT MAX(PaymentId) FROM payments)",
                  (err, result) => {
                    if (err) {
                      console.log(err);
                    } else {
                      lastPaymentDeleted = true;
                    }
                  }
                );
              } while (!lastPaymentDeleted);
            } else {
              res.status(200).send("payment added successfully");
            }
          }
        );
      }
    }
  );
});

// ### COUNTS ###

// ### C-PAYMENTS ###
// Count all ticket payments made group by spot
router.get("/count/payments/all", (req, res) => {
  db.query(
    "SELECT s.SpotId, s.SpotName, s.Price, CAST(COUNT(p.SpotId) AS INTEGER) FROM spots s LEFT JOIN payments p ON s.SpotId = p.SpotId GROUP BY s.SpotId ORDER BY s.SpotId ASC",
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Count today ticket payments made group by spot
router.get("/count/payments/today/spots", (req, res) => {
  const today = new Date();
  const dayQuery = "EXTRACT(DAY FROM DepositTimestamp)";
  const monthQuery = "EXTRACT(MONTH FROM DepositTimestamp)";
  const yearQuery = "EXTRACT(YEAR FROM DepositTimestamp)";
  db.query(
    `SELECT s.SpotId, s.SpotName, s.Price, CAST(COUNT(p.SpotId) AS INTEGER) FROM spots s LEFT JOIN payments p ON s.SpotId = p.SpotId WHERE ${dayQuery} = $1 AND ${monthQuery} = $2 AND ${yearQuery} = $3 GROUP BY s.SpotId ORDER BY s.SpotId ASC`,
    [today.getDate(), today.getMonth() + 1, today.getFullYear()],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Count monthly ticket payments made group by day then GROUP BY Spot
router.get("/count/payments/monthly/:month/spots", (req, res) => {
  const month = req.params.month;
  const monthQuery = "EXTRACT(MONTH FROM PaymentTimestamp)";
  const dayQuery = "EXTRACT(DAY FROM PaymentTimestamp)";
  db.query(
    `SELECT ${dayQuery} AS day, s.SpotId, s.SpotName, s.Price, CAST(COUNT(p.SpotId) AS INTEGER) FROM spots s LEFT JOIN payments p ON s.SpotId = p.SpotId WHERE ${monthQuery} = $1 GROUP BY ${dayQuery}, s.SpotId ORDER BY ${dayQuery} ASC, s.SpotId ASC`,
    [month],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Count annual ticket payments made group by month then GROUP BY Spot
router.get("/count/payments/annual/:year/spots", (req, res) => {
  const year = req.params.year;
  const yearQuery = "EXTRACT(YEAR FROM PaymentTimestamp)";
  const monthQuery = "EXTRACT(MONTH FROM PaymentTimestamp)";
  db.query(
    `SELECT ${monthQuery} AS month, s.SpotId, s.SpotName, s.Price, CAST(COUNT(p.SpotId) AS INTEGER) FROM spots s LEFT JOIN payments p ON s.SpotId = p.SpotId WHERE ${yearQuery} = $1 GROUP BY ${monthQuery}, s.SpotId ORDER BY ${monthQuery} ASC, s.SpotId ASC`,
    [year],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Count monthly ticket payments made in ALL SPOT group by day
router.get("/count/payments/monthly/:month", (req, res) => {
  const month = req.params.month;
  const monthQuery = "EXTRACT(MONTH FROM PaymentTimestamp)";
  const dayQuery = "EXTRACT(DAY FROM PaymentTimestamp)";
  db.query(
    `SELECT ${dayQuery} AS day, CAST(COUNT(PaymentId) AS INTEGER) FROM payments WHERE ${monthQuery} = $1 GROUP BY ${dayQuery} ORDER BY ${dayQuery} ASC`,
    [month],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Count annual ticket payments made in ALL SPOT group by month
router.get("/count/payments/annual/:year", (req, res) => {
  const year = req.params.year;
  const yearQuery = "EXTRACT(YEAR FROM PaymentTimestamp)";
  const monthQuery = "EXTRACT(MONTH FROM PaymentTimestamp)";
  db.query(
    `SELECT ${monthQuery} AS month, CAST(COUNT(PaymentId) AS INTEGER) FROM payments WHERE ${yearQuery} = $1 GROUP BY ${monthQuery} ORDER BY ${monthQuery} ASC`,
    [year],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// ### C-DEPOSITS ###
// Count all deposits made and total amount
router.get("/count/deposits/all", (req, res) => {
  db.query(
    "SELECT CAST(COUNT(DepositId) AS INTEGER), CAST(SUM(Amount) AS INTEGER) FROM deposits",
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows[0]);
      }
    }
  );
});

// Count today deposits and total amount
router.get("/count/deposits/today", (req, res) => {
  const today = new Date();
  const dayQuery = "EXTRACT(DAY FROM DepositTimestamp)";
  const monthQuery = "EXTRACT(MONTH FROM DepositTimestamp)";
  const yearQuery = "EXTRACT(YEAR FROM DepositTimestamp)";
  db.query(
    `SELECT CAST(COUNT(DepositId) AS INTEGER), CAST(SUM(Amount) AS INTEGER) FROM deposits WHERE ${dayQuery} = $1 AND ${monthQuery} = $2 AND ${yearQuery} = $3`,
    [today.getDate(), today.getMonth() + 1, today.getFullYear()],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows[0]);
      }
    }
  );
});

// Count monthly deposits and total amount group by day
router.get("/count/deposits/monthly/:month", (req, res) => {
  const month = req.params.month;
  const monthQuery = "EXTRACT(MONTH FROM DepositTimestamp)";
  const dayQuery = "EXTRACT(DAY FROM DepositTimestamp)";
  db.query(
    `SELECT ${dayQuery} AS day, CAST(COUNT(DepositId) AS INTEGER), CAST(SUM(Amount) AS INTEGER) FROM deposits WHERE ${monthQuery} = $1 GROUP BY ${dayQuery} ORDER BY ${dayQuery} ASC`,
    [month],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows[0]);
      }
    }
  );
});

// Count annual deposits and total amount group by month
router.get("/count/deposits/annual/:year", (req, res) => {
  const year = req.params.year;
  const yearQuery = "EXTRACT(YEAR FROM DepositTimestamp)";
  const monthQuery = "EXTRACT(MONTH FROM DepositTimestamp)";
  db.query(
    `SELECT ${monthQuery} AS month, CAST(COUNT(DepositId) AS INTEGER), CAST(SUM(Amount) AS INTEGER) FROM deposits WHERE ${yearQuery} = $1 GROUP BY ${monthQuery} ORDER BY ${monthQuery} ASC`,
    [year],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows[0]);
      }
    }
  );
});


// ### READER ###
// A reader is used to read the card of a customer

// Check Customer Validity : Return All Customer Data of A Certain Customer
router.get("/reader/customers/validate/:id", (req, res) => {
  const id = req.params.id;
  db.query(
    "SELECT * FROM customers WHERE CustomerId = $1",
    [id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Check Customer Active Status : Return IsActive of A Certain Customer
router.get("/reader/customers/active/:id", (req, res) => {
  const id = req.params.id;
  db.query(
    "SELECT IsActive FROM customers WHERE CustomerId = $1",
    [id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Check Customer Balance : Return Balance of A Certain Customer
router.get("/reader/customers/balance/:id", (req, res) => {
  const id = req.params.id;
  db.query(
    "SELECT Balance FROM customers WHERE CustomerId = $1",
    [id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Customer Payment : Add A Payment of A Customer in A Spot including updating the balance of the customer
router.post("/reader/payments/add", (req, res) => {
  const { customer_id, spot_id } = req.body;
  // Perform makePayment function then return new balance
  db.query(
    "INSERT INTO payments (CustomerId, SpotId) VALUES ($1, $2)",
    [customer_id, spot_id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        // update balance in customers table
        db.query(
          "UPDATE customers SET Balance = Balance - (SELECT Price FROM spots WHERE SpotId = $1) WHERE CustomerId = $2",
          [spot_id, customer_id],
          (err, result) => {
            if (err) {
              console.log(err);
              // if error occurs, delete the last payment was made
              let lastPaymentDeleted = false;
              do {
                db.query(
                  "DELETE FROM payments WHERE PaymentId = (SELECT MAX(PaymentId) FROM payments)",
                  (err, result) => {
                    if (err) {
                      console.log(err);
                    } else {
                      lastPaymentDeleted = true;
                    }
                  }
                );
              } while (!lastPaymentDeleted);
            } else {
              // return new balance
              db.query(
                "SELECT Balance FROM customers WHERE CustomerId = $1",
                [customer_id],
                (err, result) => {
                  if (err) {
                    console.log(err);
                  } else {
                    res.status(200).send(result.rows);
                  }
                }
              );
            }
          }
        );
      }
    }
  );
});

module.exports = router;
