const express = require("express");
const router = express.Router();
const db = require("../../../utils/database");

// ### M-SPOTS ###

// Get All Spots data
router.get("/management/spots/all", (req, res) => {
  db.query("SELECT * FROM spots ORDER BY SpotId ASC", (err, result) => {
    if (err) {
      console.log(err);
    } else {
      console.log("[API] spots data fetched successfully")
      res.status(200).send(result.rows);
    }
  });
});

// Get A Certain Spot data
router.get("/management/spots/certain/:id", (req, res) => {
  const id = req.params.id;
  db.query("SELECT * FROM spots WHERE SpotId = $1", [id], (err, result) => {
    if (err) {
      console.log(err);
    } else {
      console.log("[API] spot data fetched successfully")
      res.status(200).send(result.rows);
    }
  });
});

// Add A Spot
router.post("/management/spots/add", (req, res) => {
  const { name, price } = req.body;
  // created_at, last_modified, is_active are automatically generated by the database
  db.query(
    "INSERT INTO spots (SpotName, Price) VALUES ($1, $2)",
    [name, price],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        console.log("[API] spot added successfully");
        res.status(200).send("spot added successfully");
      }
    }
  );
});

// Update A Spot data
router.patch("/management/spots/update/:id", (req, res) => {
  const id = req.params.id;
  const { name, price } = req.body;
  db.query(
    "UPDATE spots SET SpotName = $1, Price = $2 WHERE SpotId = $3",
    [name, price, id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        console.log("[API] spot updated successfully");
        res.status(200).send("spot updated successfully");
      }
    }
  );
});

// Delete A Spot
router.delete("/management/spots/delete/:id", (req, res) => {
  const id = req.params.id;
  db.query("DELETE FROM spots WHERE SpotId = $1", [id], (err, result) => {
    if (err) {
      console.log(err);
    } else {
      console.log("[API] spot deleted successfully");
      res.status(200).send("spot deleted successfully");
    }
  });
});

module.exports = router;