const express = require("express");
const router = express.Router();
const db = require("../../database");

// ### DEPOSITS ###

// Get All Deposits data
router.get("/deposits/all", (req, res) => {
  db.query("SELECT * FROM deposits ORDER BY DepositId ASC", (err, result) => {
    if (err) {
      console.log(err);
    } else {
      res.status(200).send(result.rows);
    }
  });
});

// Get Deposit data of A Certain Customer
router.get("/deposits/certain/customers/:id", (req, res) => {
  const id = req.params.id;
  db.query(
    "SELECT * FROM deposits WHERE CustomerId = $1 ORDER BY DepositId ASC",
    [id],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        res.status(200).send(result.rows);
      }
    }
  );
});

// Add A Deposit of A Customer
router.post("/deposits/add", (req, res) => {
  const { customer_id, amount } = req.body;
  console.log(customer_id, amount);
  // DepositTimestamp is automatically generated by the database
  // insert data to deposits table and update balance in customers table
  db.query(
    "INSERT INTO deposits (CustomerId, Amount) VALUES ($1, $2)",
    [customer_id, amount],
    (err, result) => {
      if (err) {
        console.log(err);
      } else {
        // update balance in customers table
        db.query(
          "UPDATE customers SET Balance = Balance + $1 WHERE CustomerId = $2",
          [amount, customer_id],
          (err, result) => {
            if (err) {
              console.log(err);
              // if error occurs, delete the last deposit was made
              let lastDepositDeleted = false;
              do {
                db.query(
                  "DELETE FROM deposits WHERE DepositId = (SELECT MAX(DepositId) FROM deposits)",
                  (err, result) => {
                    if (err) {
                      console.log(err);
                    } else {
                      lastDepositDeleted = true;
                    }
                  }
                );
              } while (!lastDepositDeleted);
            } else {
              res.status(200).send("deposit added successfully");
            }
          }
        );
      }
    }
  );
});

module.exports = router;